### ISSUE TITLE
Additional Sensors for Net Metering Customers

### ISSUE THREAD

**Issue by dorgan** [dotKrad/hass-fpl#12] opened 2021-06-11 15:52 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would nice to be able to track on a daily basis home much power FPL is reporting you have received and/or they have delivered.

**Describe alternatives you've considered**
I also have a sense energy monitor, but they do not line up, so making sure they are not WAY off is good.

**Additional context**
The Data can be seen on the following request:
https://www.fpl.com/dashboard-api/resources/account/<account_number>/energyService/<account_number>

Sample Request Payload:
```
{
    "status": 2,
    "channel": "WEB",
    "amrFlag": "Y",
    "accountType": "RESIDENTIAL",
    "revCode": "1",
    "premiseNumber": "<premise_number>",
    "meterNo": "<meter_number>",
    "projectedBillFlag": false,
    "billComparisionFlag": false,
    "monthlyFlag": false,
    "frequencyType": "Daily",
    "lastBilledDate": "<lastBillDated>",
    "applicationPage": "resDashBoard",
    "startDate": "",
    "endDate": ""
}
```

There may be other way to get to this data, and honestly i dont even need it broken down by day, if it can be pulled in and updated i'll have historical just from it updating

Sample Response:
```
{
    "data": {
        "DailyUsage": {
            "premiseNumber": "XXXXX",
            "accountNumber": "XXXXXX",
            "readingType": "daily",
            "startDate": "20210609",
            "endDate": "20210610",
            "data": [{
                "kwhUsed": -12,
                "billingCharge": 0.33,
                "temperature": 86.0,
                "billingDayName": "Wed",
                "date": "20210609",
                "holiday": "false",
                "missingDay": "false",
                "billingDay": "09",
                "billingMonth": "Jun",
                "billingYear": "2021",
                "humidity": 82.0,
                "readTime": "2021-06-09T00:00:00.000-04:00",
                "reading": 7468.3932,
                "averageHighTemperature": 86,
                "averageLowTemperature": 74,
                "averageMidTemperature": 80,
                "averageHighHumidity": 82,
                "averageLowHumidity": 1,
                "averageMidHumidity": 45,
                "readingType": "AMI",
                "netDeliveredKwh": 36.5184,
                "netReceivedKwh": 48.9492,
                "netDeliveredReading": 7468.3932,
                "netReceivedReading": 8147.0052,
                "meterNumber": "KCD750N"
            }, {
                "kwhUsed": -6,
                "billingCharge": 0.33,
                "temperature": 89.0,
                "billingDayName": "Thu",
                "date": "20210610",
                "holiday": "false",
                "missingDay": "false",
                "billingDay": "10",
                "billingMonth": "Jun",
                "billingYear": "2021",
                "humidity": 81.0,
                "readTime": "2021-06-10T00:00:00.000-04:00",
                "reading": 7504.9116,
                "averageHighTemperature": 89,
                "averageLowTemperature": 76,
                "averageMidTemperature": 83,
                "averageHighHumidity": 81,
                "averageLowHumidity": 1,
                "averageMidHumidity": 43,
                "readingType": "AMI",
                "netDeliveredKwh": 35.1348,
                "netReceivedKwh": 41.0472,
                "netDeliveredReading": 7504.9116,
                "netReceivedReading": 8195.9544,
                "meterNumber": "KCD750N"
            }],
            "maxTemperature": 0.0,
            "minTemperature": 0.0,
            "maxBillingCharge": 0.0,
            "minBillingCharge": 0.0,
            "maxKwh": 0.0,
            "minKwh": 0.0,
            "maxHumidity": 0.0,
            "minHumidity": 0.0
        }
    }
}
```

**Comment by dotKrad** [comment] 2021-06-11 16:00
is this the field you want ?
"kwhUsed": -12

**Comment by dorgan** [comment] 2021-06-11 16:04
Yes that would be GREAT!

**Comment by dotKrad** [comment] 2021-08-10 03:29
if the issue is resolved please close it

**Closed** 2021-09-15 14:34 UTC
